// Deterministic seed generator for Bushi. Emits seed/seed.sql — realistic demo
// data: organizations, schools, coaches, 60+ athletes, 2 tournaments, divisions,
// entries, completed matches, sponsors and rankings. Deterministic so the seed
// is reproducible in CI (no Math.random / Date.now — a fixed base time is used).
//
//   node packages/db/seed/generate-seed.mjs
//
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BASE = 1751328000000; // 2025-07-01T00:00:00Z, fixed for reproducibility

// Tiny deterministic PRNG (mulberry32) so runs are identical.
function rng(seed) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = rng(42);
const pick = (arr) => arr[Math.floor(rand() * arr.length)];
// Globally-unique, readable id. A monotonic counter guarantees no collisions
// even when callers pass the same prefix/index pair.
let _seq = 0;
const uid = (p) => `${p}-${String(_seq++).padStart(6, '0')}`;
const esc = (s) => (s == null ? 'NULL' : `'${String(s).replace(/'/g, "''")}'`);

const lines = [];
const push = (sql) => lines.push(sql);
push('-- Bushi seed data (generated by generate-seed.mjs) — do not edit by hand.');
push('PRAGMA foreign_keys = OFF;');
push('BEGIN TRANSACTION;');

const styles = ['karate', 'bjj', 'taekwondo', 'judo', 'kickboxing'];
const firstNames = ['Kenji', 'Mia', 'Diego', 'Aisha', 'Liam', 'Sofia', 'Noah', 'Emma', 'Kai', 'Yuki', 'Marcus', 'Lena', 'Ravi', 'Nina', 'Omar', 'Grace', 'Tomas', 'Zara', 'Ivan', 'Chloe'];
const lastNames = ['Tanaka', 'Silva', 'Kim', 'Johnson', 'Nguyen', 'Garcia', 'Ivanov', 'Okafor', 'Rossi', 'Patel', 'Muller', 'Costa', 'Haddad', 'Novak', 'Reyes', 'Dubois'];
const cities = [['San Jose', 'CA', 'US'], ['Austin', 'TX', 'US'], ['Denver', 'CO', 'US'], ['Miami', 'FL', 'US'], ['Portland', 'OR', 'US']];
const belts = { bjj: ['White', 'Blue', 'Purple', 'Brown', 'Black'], karate: ['White', 'Green', 'Brown', 'Black'], taekwondo: ['White', 'Blue', 'Red', 'Black'], judo: ['White', 'Green', 'Brown', 'Black'], kickboxing: ['Novice', 'Intermediate', 'Advanced'] };

// --- users + org ---
push(`INSERT INTO users (id,email,password_hash,email_verified_at,status,created_at,updated_at) VALUES
  (${esc('user-admin')},${esc('admin@bushi.app')},${esc('seed$disabled')},${BASE},'active',${BASE},${BASE}),
  (${esc('user-organizer')},${esc('organizer@bushi.app')},${esc('seed$disabled')},${BASE},'active',${BASE},${BASE});`);
push(`INSERT INTO user_profiles (user_id,full_name,locale,created_at,updated_at) VALUES
  (${esc('user-admin')},${esc('Platform Admin')},'en',${BASE},${BASE}),
  (${esc('user-organizer')},${esc('Rin Watanabe')},'en',${BASE},${BASE});`);
push(`INSERT INTO organizations (id,name,slug,plan_tier,created_by,created_at,updated_at) VALUES
  (${esc('org-open')},${esc('Open Circuit Martial Arts')},${esc('open-circuit')},'pro',${esc('user-organizer')},${BASE},${BASE});`);
push(`INSERT INTO organization_memberships (id,org_id,user_id,role,created_at,updated_at) VALUES
  (${esc('mem-admin')},${esc('org-open')},${esc('user-admin')},'platform_admin',${BASE},${BASE}),
  (${esc('mem-org')},${esc('org-open')},${esc('user-organizer')},'organizer',${BASE},${BASE});`);
push(`INSERT INTO subscriptions (id,org_id,tier,status,current_period_end,created_at,updated_at) VALUES
  (${esc('sub-open')},${esc('org-open')},'pro','active',${BASE + 2592000000},${BASE},${BASE});`);

// --- schools + staff + athletes ---
const schoolNames = ['Ronin Academy', 'Ironbound BJJ', 'Summit Taekwondo', 'Bushido Judo Club', 'Vanguard Striking', 'Meridian Martial Arts'];
const schools = [];
const athletes = [];
let athleteNo = 0;
schoolNames.forEach((name, i) => {
  const id = uid('school', i);
  const [city, region, country] = cities[i % cities.length];
  const st = [pick(styles), pick(styles)];
  schools.push({ id, style: st[0] });
  push(`INSERT INTO schools (id,org_id,name,slug,styles,bio,city,region,country,is_public,created_at,updated_at) VALUES (${esc(id)},${esc('org-open')},${esc(name)},${esc(name.toLowerCase().replace(/[^a-z0-9]+/g, '-'))},${esc(JSON.stringify([...new Set(st)]))},${esc(`${name} — disciplined training across ${st.join(' & ')}.`)},${esc(city)},${esc(region)},${esc(country)},1,${BASE},${BASE});`);
  push(`INSERT INTO public_school_profiles (school_id,headline,about,premium,updated_at) VALUES (${esc(id)},${esc(`Train with purpose at ${name}`)},${esc('Competition-focused program with a proven tournament record.')},${i < 2 ? 1 : 0},${BASE});`);
  push(`INSERT INTO school_staff (id,school_id,name,role,created_at,updated_at) VALUES (${esc(uid('staff', i))},${esc(id)},${esc(`Coach ${pick(lastNames)}`)},'head_coach',${BASE},${BASE});`);
  // 10-12 athletes per school
  const count = 10 + (i % 3);
  for (let a = 0; a < count; a++) {
    const aid = uid('ath', athleteNo++);
    const style = pick(st);
    const belt = pick(belts[style] || ['White']);
    const age = 12 + Math.floor(rand() * 25);
    const dob = new Date(BASE - age * 31557600000).toISOString().slice(0, 10);
    const weight = 45 + Math.floor(rand() * 55);
    const fn = pick(firstNames);
    const ln = pick(lastNames);
    athletes.push({ id: aid, style, weight, age, name: `${fn} ${ln}`, schoolId: id });
    push(`INSERT INTO athletes (id,school_id,first_name,last_name,date_of_birth,gender,primary_style,belt_rank,is_public,created_at,updated_at) VALUES (${esc(aid)},${esc(id)},${esc(fn)},${esc(ln)},${esc(dob)},${esc(pick(['male', 'female']))},${esc(style)},${esc(belt)},1,${BASE},${BASE});`);
    push(`INSERT INTO athlete_measurements (id,athlete_id,measured_at,weight_kg,created_at) VALUES (${esc(uid('meas', athleteNo))},${esc(aid)},${BASE},${weight},${BASE});`);
  }
  // ranking sample
  push(`INSERT INTO school_rankings (id,school_id,style,region,points,rank,period,created_at,updated_at) VALUES (${esc(uid('rank', i))},${esc(id)},${esc(st[0])},${esc(region)},${1000 - i * 90},${i + 1},'2026-Q3',${BASE},${BASE});`);
});

// --- tournaments ---
const tournaments = [
  { id: 'tour-summer', name: 'Bushi Summer Open 2026', slug: 'bushi-summer-open-2026', status: 'registration_open', start: '2026-08-15', styles: ['karate', 'bjj', 'taekwondo'] },
  { id: 'tour-winter', name: 'Bushi Winter Classic 2026', slug: 'bushi-winter-classic-2026', status: 'completed', start: '2026-02-08', styles: ['bjj', 'judo'] },
];
for (const t of tournaments) {
  push(`INSERT INTO tournaments (id,org_id,name,slug,styles,status,description,start_date,venue_name,city,region,country,is_public,registration_opens_at,registration_closes_at,created_at,updated_at) VALUES (${esc(t.id)},${esc('org-open')},${esc(t.name)},${esc(t.slug)},${esc(JSON.stringify(t.styles))},${esc(t.status)},${esc('A premier all-styles tournament on the Bushi platform.')},${esc(t.start)},${esc('Grand Pavilion Arena')},${esc('San Jose')},${esc('CA')},${esc('US')},1,${BASE},${BASE + 5184000000},${BASE},${BASE});`);
  for (let m = 1; m <= 4; m++) {
    push(`INSERT INTO mats (id,tournament_id,mat_number,name,created_at) VALUES (${esc(uid(t.id + '-mat', m))},${esc(t.id)},${m},${esc('Mat ' + m)},${BASE});`);
  }
}

// divisions + entries + matches for the completed winter tournament
const divisions = [
  { id: 'div-bjj-adult', tour: 'tour-winter', name: 'BJJ Adult Blue -76kg', style: 'bjj', format: 'single_elimination' },
  { id: 'div-judo-teen', tour: 'tour-winter', name: 'Judo Teen -60kg', style: 'judo', format: 'single_elimination' },
  { id: 'div-karate-open', tour: 'tour-summer', name: 'Karate Open Kumite', style: 'karate', format: 'single_elimination' },
];
for (const d of divisions) {
  push(`INSERT INTO divisions (id,tournament_id,name,style,format,status,created_at,updated_at) VALUES (${esc(d.id)},${esc(d.tour)},${esc(d.name)},${esc(d.style)},${esc(d.format)},${d.tour === 'tour-winter' ? "'complete'" : "'open'"},${BASE},${BASE});`);
  const pool = athletes.filter((a) => a.style === d.style).slice(0, 8);
  const entrants = pool.length >= 4 ? pool.slice(0, 8) : athletes.slice(0, 8);
  entrants.forEach((a, idx) => {
    push(`INSERT INTO division_entries (id,division_id,athlete_id,seed,status,created_at,updated_at) VALUES (${esc(uid(d.id + '-e', idx))},${esc(d.id)},${esc(a.id)},${idx + 1},'checked_in',${BASE},${BASE});`);
  });
  // completed matches only for the winter tournament
  if (d.tour === 'tour-winter' && entrants.length >= 4) {
    const methods = ['submission', 'points', 'decision', 'ippon'];
    for (let r = 0; r < Math.min(3, entrants.length - 1); r++) {
      const a = entrants[r * 2 % entrants.length];
      const b = entrants[(r * 2 + 1) % entrants.length];
      const mid = uid(d.id + '-m', r);
      const winner = rand() > 0.5 ? a : b;
      push(`INSERT INTO matches (id,tournament_id,division_id,round,ordinal,label,status,winner_athlete_id,method,completed_at,created_at,updated_at) VALUES (${esc(mid)},${esc(d.tour)},${esc(d.id)},${r + 1},0,${esc('Round ' + (r + 1))},'completed',${esc(winner.id)},${esc(pick(methods))},${BASE},${BASE},${BASE});`);
      push(`INSERT INTO match_participants (id,match_id,athlete_id,corner,score,penalties,created_at) VALUES (${esc(uid(mid + 'a', r))},${esc(mid)},${esc(a.id)},'a',${Math.floor(rand() * 12)},0,${BASE});`);
      push(`INSERT INTO match_participants (id,match_id,athlete_id,corner,score,penalties,created_at) VALUES (${esc(uid(mid + 'b', r))},${esc(mid)},${esc(b.id)},'b',${Math.floor(rand() * 12)},0,${BASE});`);
    }
  }
}

// sponsors
push(`INSERT INTO sponsors (id,tournament_id,name,tier,website,created_at) VALUES
  (${esc('spon-1')},${esc('tour-summer')},${esc('Katana Gear Co.')},'gold',${esc('https://example.com')},${BASE}),
  (${esc('spon-2')},${esc('tour-summer')},${esc('Dojo Nutrition')},'silver',${esc('https://example.com')},${BASE});`);

// prompt templates (used by the AI layer)
push(`INSERT INTO prompt_templates (id,key,version,description,system_prompt,user_template,model,created_at,updated_at) VALUES
  (${esc('pt-promo')},${esc('tournament.promo_copy')},1,${esc('Promo copy for a tournament')},${esc('You are a sharp martial-arts marketing copywriter. Tone: disciplined, premium, athletic. Avoid cliches.')},${esc('Write launch copy for {{name}} on {{start_date}} in {{city}}. Styles: {{styles}}.')},${esc('@cf/meta/llama-3.1-8b-instruct')},${BASE},${BASE}),
  (${esc('pt-recap')},${esc('tournament.recap')},1,${esc('Post-event recap')},${esc('You write concise, energetic post-event recaps for martial arts tournaments.')},${esc('Write a recap for {{name}}. Divisions: {{divisions}}. Notable results: {{results}}.')},${esc('@cf/meta/llama-3.1-8b-instruct')},${BASE},${BASE});`);

push('COMMIT;');
push('PRAGMA foreign_keys = ON;');

const out = join(__dirname, 'seed.sql');
writeFileSync(out, lines.join('\n') + '\n');
console.log(`Wrote ${out} (${lines.length} statements, ${athletes.length} athletes)`);
